FROM golang:1.26.1-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/server .

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app
COPY --from=builder /build/server /server
COPY 100k-most-used-passwords-NCSC.txt /app/

EXPOSE 8080
CMD ["/server"]
